### PR TITLE
Fix rm/mv prompts when using OMZSH! common-aliases

### PR DESCRIPTION
**Pull request by felipecrs**
Follow-up: https://github.com/sdkman/sdkman-cli/pull/851

### CODE REVIEW

**Comment by felipecrs** [comment]
@marc0der can you look on this? It's very simple and it's ready to be merged.

**Comment by marc0der** [comment]
Hi @felipecrs, merging this can't do much harm but I'm curious to know why you get these promots. Reason being that I use oh-my-zsh and have never had such an issue. Could it be that you have some stray config in your ZSH profile that is causing this?

**Comment by felipecrs** [comment]
Hi @marc0der. Yes, please see the linked issue, more specifically at https://github.com/sdkman/sdkman-cli/pull/851#issuecomment-756438119.

**Comment by marc0der** [comment]
Thanks for contacting!

**Comment by felipecrs** [comment]
My pleasure! :D

**Pull request merged**
