### PR TITLE
Fixes #39

### LINKED ISSUE #39: Zulu jmc is broken on Linux
The `jmc` symbolic link to `zmc` in **8.1.1.51-zulu** version of JMC on Linux should be `../Azul Mission Control/zmc` (instead of being `../Zulu Mission Control/zmc`).

I am guessing https://github.com/sdkman/sdkman-hooks/blob/980175e18030828cb957dc05010d82dbb3150b73/app/controllers/HooksController.scala#L102-L111 needs to be tweaked to fix this issue.

### PR DESCRIPTION
**Pull request by rvprasad**
Fixes name of Zulu's mission control app.

### CODE REVIEW

**Comment by marc0der** [comment]
Thanks for the contribution!

**Comment by marc0der** [comment]
BTW, I'll deploy this over the next few days.

**Comment by marc0der** [comment]
@rvprasad This has now been released as v1.3.4 and fixes the problem. Verified on my own Linux laptop.

**Comment by rvprasad** [comment]
Yep, it works :)

BTW, testing changes to sdkman is very easy.  In turn, this setup makes contributing to sdkman easy :)  Thanks for the setup!

**Pull request merged**
